[package]
name = "ak-inflate2"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2024"

[features]
std = []

default = ["std"]

[dependencies]
hex-literal = "0.3.3"
embedded-io-async = "0.6.1"
heapless = "0.8"

[dev-dependencies]
futures-test = "0.3.3"
